name       : python-seaborn
version    : 0.11.2
release    : 6
source     :
    - https://github.com/mwaskom/seaborn/archive/refs/tags/v0.11.2.tar.gz : 693e3877d7608e08201feb6b99a7c9fce06ecaa88acbb8c3e928bdff9feb8515
license    : BSD-3-Clause
component  : programming.python
summary    : Python visualization library based on matplotlib
description: |
    Seaborn is a library for making attractive and informative statistical
    graphics in Python. It is built on top of matplotlib and tightly
    integrated with the PyData stack, including support for numpy and pandas
    data structures and statistical routines from scipy and statsmodels.
builddeps :
    - matplotlib
    - python-pandas
    - python-pytest # check
    - scipy
rundeps    :
    - matplotlib
    - python-pandas
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
