name       : python-seaborn
version    : 0.9.0
release    : 3
source     :
    - https://github.com/mwaskom/seaborn/archive/v0.9.0.tar.gz : e2910b86f719ceecd09350071cb68e7531d236d087d04515b961363dd7208e6f
license    : BSD-3-Clause
component  : programming.python
summary    : Python visualization library based on matplotlib
description: |
    Seaborn is a library for making attractive and informative statistical
    graphics in Python. It is built on top of matplotlib and tightly
    integrated with the PyData stack, including support for numpy and pandas
    data structures and statistical routines from scipy and statsmodels.
rundeps    :
    - matplotlib
    - python-pandas
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
