name       : python-seaborn
version    : 0.12.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/s/seaborn/seaborn-0.12.0.tar.gz : 893f17292d8baca616c1578ddb58eb25c72d622f54fc5ee329c8207dc9b57b23
homepage   : https://seaborn.pydata.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Python visualization library based on matplotlib
description: |
    Seaborn is a library for making attractive and informative statistical graphics in Python. It is built on top of matplotlib and tightly integrated with the PyData stack, including support for numpy and pandas data structures and statistical routines from scipy and statsmodels.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
    - matplotlib       # check
    - python-pandas    # check
    - python-pytest    # check
    - scipy            # check
rundeps    :
    - matplotlib
    - python-pandas
    - python-statsmodels
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
