name       : python-seaborn
version    : 0.8.1
release    : 1
source     :
    - https://github.com/mwaskom/seaborn/archive/v0.8.1.tar.gz : a37331d4056f557013028158f8cbbcd5d21737e8b2b1542b40589ada04f3e7ce
license    : BSD-3-Clause
component  : programming.python
summary    : Python visualization library based on matplotlib
description: |
    Seaborn is a library for making attractive and informative statistical
    graphics in Python. It is built on top of matplotlib and tightly
    integrated with the PyData stack, including support for numpy and pandas
    data structures and statistical routines from scipy and statsmodels.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - scipy
    - matplotlib
    - python-pandas
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

